/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSatellitesRouteImport } from './routes/api/satellites'
import { Route as ApiPhotoRouteImport } from './routes/api/photo'
import { Route as ApiFlightsRouteImport } from './routes/api/flights'
import { Route as ApiFlightTrackRouteImport } from './routes/api/flight-track'
import { Route as ApiEnrichmentRouteImport } from './routes/api/enrichment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSatellitesRoute = ApiSatellitesRouteImport.update({
  id: '/api/satellites',
  path: '/api/satellites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotoRoute = ApiPhotoRouteImport.update({
  id: '/api/photo',
  path: '/api/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlightsRoute = ApiFlightsRouteImport.update({
  id: '/api/flights',
  path: '/api/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlightTrackRoute = ApiFlightTrackRouteImport.update({
  id: '/api/flight-track',
  path: '/api/flight-track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrichmentRoute = ApiEnrichmentRouteImport.update({
  id: '/api/enrichment',
  path: '/api/enrichment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/enrichment': typeof ApiEnrichmentRoute
  '/api/flight-track': typeof ApiFlightTrackRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/satellites': typeof ApiSatellitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/enrichment': typeof ApiEnrichmentRoute
  '/api/flight-track': typeof ApiFlightTrackRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/satellites': typeof ApiSatellitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/enrichment': typeof ApiEnrichmentRoute
  '/api/flight-track': typeof ApiFlightTrackRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/satellites': typeof ApiSatellitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/enrichment'
    | '/api/flight-track'
    | '/api/flights'
    | '/api/photo'
    | '/api/satellites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/enrichment'
    | '/api/flight-track'
    | '/api/flights'
    | '/api/photo'
    | '/api/satellites'
  id:
    | '__root__'
    | '/'
    | '/api/enrichment'
    | '/api/flight-track'
    | '/api/flights'
    | '/api/photo'
    | '/api/satellites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEnrichmentRoute: typeof ApiEnrichmentRoute
  ApiFlightTrackRoute: typeof ApiFlightTrackRoute
  ApiFlightsRoute: typeof ApiFlightsRoute
  ApiPhotoRoute: typeof ApiPhotoRoute
  ApiSatellitesRoute: typeof ApiSatellitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/satellites': {
      id: '/api/satellites'
      path: '/api/satellites'
      fullPath: '/api/satellites'
      preLoaderRoute: typeof ApiSatellitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photo': {
      id: '/api/photo'
      path: '/api/photo'
      fullPath: '/api/photo'
      preLoaderRoute: typeof ApiPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flights': {
      id: '/api/flights'
      path: '/api/flights'
      fullPath: '/api/flights'
      preLoaderRoute: typeof ApiFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flight-track': {
      id: '/api/flight-track'
      path: '/api/flight-track'
      fullPath: '/api/flight-track'
      preLoaderRoute: typeof ApiFlightTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrichment': {
      id: '/api/enrichment'
      path: '/api/enrichment'
      fullPath: '/api/enrichment'
      preLoaderRoute: typeof ApiEnrichmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEnrichmentRoute: ApiEnrichmentRoute,
  ApiFlightTrackRoute: ApiFlightTrackRoute,
  ApiFlightsRoute: ApiFlightsRoute,
  ApiPhotoRoute: ApiPhotoRoute,
  ApiSatellitesRoute: ApiSatellitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
