# Generated by Django 5.1.15 on 2026-05-10 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('icao24', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('callsign', models.CharField(blank=True, default='', max_length=10)),
                ('origin_country', models.CharField(blank=True, default='', max_length=100)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_states', models.PositiveIntegerField(default=0)),
                ('total_anomalies', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_flights', models.PositiveIntegerField(default=0)),
                ('airborne', models.PositiveIntegerField(default=0)),
                ('on_ground', models.PositiveIntegerField(default=0)),
                ('anomaly_count', models.PositiveIntegerField(default=0)),
                ('anomaly_rate', models.FloatField(default=0.0, help_text='Anomalies / total flights %')),
                ('avg_ml_score', models.FloatField(default=0.0)),
                ('countries_active', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'System metrics',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('ghost', 'Ghost Flight'), ('squawk_7500', 'Hijack (7500)'), ('squawk_7600', 'Radio Failure (7600)'), ('squawk_7700', 'Emergency (7700)'), ('low_fast', 'Low & Fast'), ('rapid_descent', 'Rapid Descent'), ('signal_lost', 'Signal Lost'), ('ml_anomaly', 'ML-Detected Anomaly'), ('speed_anomaly', 'Unusual Speed'), ('altitude_anomaly', 'Unusual Altitude'), ('heading_anomaly', 'Unusual Heading Change'), ('position_anomaly', 'Position Jump')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Combined rule + ML confidence (0-100)')),
                ('ml_score', models.FloatField(blank=True, help_text='Raw Isolation Forest anomaly score', null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_events', to='flights.aircraft')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['is_active', '-detected_at'], name='flights_ano_is_acti_fd0ca7_idx'), models.Index(fields=['anomaly_type', '-detected_at'], name='flights_ano_anomaly_da4bc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('points', models.JSONField(default=list, help_text='Array of {lat, lon, alt, time, speed} objects')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('point_count', models.PositiveIntegerField(default=0)),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='flights.aircraft')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['aircraft', 'session_id'], name='flights_fli_aircraf_f1c930_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlightState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('baro_altitude', models.FloatField(blank=True, help_text='Barometric altitude in meters', null=True)),
                ('geo_altitude', models.FloatField(blank=True, help_text='Geometric altitude in meters', null=True)),
                ('velocity', models.FloatField(blank=True, help_text='Ground speed in m/s', null=True)),
                ('vertical_rate', models.FloatField(blank=True, help_text='Vertical rate in m/s', null=True)),
                ('true_track', models.FloatField(blank=True, help_text='True heading in degrees', null=True)),
                ('squawk', models.CharField(blank=True, max_length=4, null=True)),
                ('on_ground', models.BooleanField(default=False)),
                ('spi', models.BooleanField(default=False)),
                ('position_source', models.SmallIntegerField(default=0)),
                ('last_contact', models.FloatField(default=0, help_text='Unix epoch of last contact')),
                ('time_position', models.FloatField(blank=True, help_text='Unix epoch of last position', null=True)),
                ('ml_anomaly_score', models.FloatField(blank=True, help_text='Isolation Forest score (-1 to 1)', null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='flights.aircraft')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['aircraft', 'timestamp'], name='flights_fli_aircraf_9aab4c_idx'), models.Index(fields=['timestamp'], name='flights_fli_timesta_c380a4_idx')],
            },
        ),
    ]
