# Generated by Django 5.1.15 on 2026-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='category',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='flightstate',
            name='category',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
