# Generated by Django 5.1.15 on 2026-05-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_aircraft_category_flightstate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(blank=True, default='', help_text='Aircraft type/model', max_length=100),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='data_source',
            field=models.CharField(blank=True, default='', help_text='Last data source', max_length=20),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='owner',
            field=models.CharField(blank=True, default='', help_text='Registered owner', max_length=200),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='registration',
            field=models.CharField(blank=True, default='', help_text='Registration code', max_length=20),
        ),
        migrations.AddField(
            model_name='flightstate',
            name='data_source',
            field=models.CharField(blank=True, default='', help_text='Source: opensky, adsb_one, airplanes_live, ogn, faa_radar, uat, satellite', max_length=20),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='source_counts',
            field=models.JSONField(blank=True, default=dict, help_text='Per-source aircraft counts: {opensky: N, adsb_one: N, ...}'),
        ),
    ]
