# Generated by Django 5.1.15 on 2026-05-17 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_add_data_source_and_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftProfile',
            fields=[
                ('aircraft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='flights.aircraft')),
                ('avg_velocity', models.FloatField(default=0, help_text='EMA mean velocity (m/s)')),
                ('std_velocity', models.FloatField(default=0, help_text='EMA std velocity')),
                ('avg_altitude', models.FloatField(default=0, help_text='EMA mean altitude (m)')),
                ('std_altitude', models.FloatField(default=0, help_text='EMA std altitude')),
                ('avg_vertical_rate', models.FloatField(default=0, help_text='EMA mean |vertical rate|')),
                ('typical_heading_variance', models.FloatField(default=0, help_text='Circular heading variance')),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('profile_data', models.JSONField(blank=True, default=dict, help_text='Full EMA profile stats')),
            ],
            options={
                'verbose_name_plural': 'Aircraft profiles',
            },
        ),
        migrations.AlterField(
            model_name='anomalyevent',
            name='anomaly_type',
            field=models.CharField(choices=[('ghost', 'Ghost Flight'), ('squawk_7500', 'Hijack (7500)'), ('squawk_7600', 'Radio Failure (7600)'), ('squawk_7700', 'Emergency (7700)'), ('low_fast', 'Low & Fast'), ('rapid_descent', 'Rapid Descent'), ('signal_lost', 'Signal Lost'), ('ml_anomaly', 'ML-Detected Anomaly'), ('speed_anomaly', 'Unusual Speed'), ('altitude_anomaly', 'Unusual Altitude'), ('heading_anomaly', 'Unusual Heading Change'), ('position_anomaly', 'Position Jump'), ('circling', 'Circling / Loitering'), ('trajectory_deviation', 'Trajectory Deviation'), ('geofence', 'Restricted Airspace'), ('proximity', 'Proximity Alert'), ('altitude_bust', 'Altitude Bust'), ('speed_envelope', 'Speed Envelope Violation'), ('behavioral', 'Behavioral Deviation')], max_length=30),
        ),
    ]
