# Generated by Django 5.1.15 on 2026-05-17 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_aircraftprofile_alter_anomalyevent_anomaly_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
