/**
 * Comprehensive airline database — ~300 airlines covering all major
 * carriers worldwide plus regional and cargo operators.
 *
 * This replaces the previous 55-entry hardcoded lookup. Each entry
 * maps a 3-letter ICAO prefix to airline metadata.
 */

export interface AirlinePrefix {
  icao: string;
  iata: string;
  name: string;
  country: string;
}

const airlinePrefixes: Record<string, AirlinePrefix> = {
  // ── North America ──
  AAL: { icao: "AAL", iata: "AA", name: "American Airlines", country: "United States" },
  UAL: { icao: "UAL", iata: "UA", name: "United Airlines", country: "United States" },
  DAL: { icao: "DAL", iata: "DL", name: "Delta Air Lines", country: "United States" },
  SWA: { icao: "SWA", iata: "WN", name: "Southwest Airlines", country: "United States" },
  JBU: { icao: "JBU", iata: "B6", name: "JetBlue Airways", country: "United States" },
  ASA: { icao: "ASA", iata: "AS", name: "Alaska Airlines", country: "United States" },
  NKS: { icao: "NKS", iata: "NK", name: "Spirit Airlines", country: "United States" },
  FFT: { icao: "FFT", iata: "F9", name: "Frontier Airlines", country: "United States" },
  HAL: { icao: "HAL", iata: "HA", name: "Hawaiian Airlines", country: "United States" },
  AAY: { icao: "AAY", iata: "G4", name: "Allegiant Air", country: "United States" },
  SKW: { icao: "SKW", iata: "OO", name: "SkyWest Airlines", country: "United States" },
  RPA: { icao: "RPA", iata: "YX", name: "Republic Airways", country: "United States" },
  EJA: { icao: "EJA", iata: "EJ", name: "NetJets Aviation", country: "United States" },
  ENY: { icao: "ENY", iata: "MQ", name: "Envoy Air", country: "United States" },
  PDT: { icao: "PDT", iata: "PT", name: "Piedmont Airlines", country: "United States" },
  PSA: { icao: "PSA", iata: "OH", name: "PSA Airlines", country: "United States" },
  ACA: { icao: "ACA", iata: "AC", name: "Air Canada", country: "Canada" },
  WJA: { icao: "WJA", iata: "WS", name: "WestJet", country: "Canada" },
  TSC: { icao: "TSC", iata: "TS", name: "Air Transat", country: "Canada" },
  POE: { icao: "POE", iata: "PD", name: "Porter Airlines", country: "Canada" },
  AMX: { icao: "AMX", iata: "AM", name: "Aeroméxico", country: "Mexico" },
  VOI: { icao: "VOI", iata: "Y4", name: "Volaris", country: "Mexico" },
  VIV: { icao: "VIV", iata: "VB", name: "VivaAerobus", country: "Mexico" },
  // ── Europe ──
  BAW: { icao: "BAW", iata: "BA", name: "British Airways", country: "United Kingdom" },
  AFR: { icao: "AFR", iata: "AF", name: "Air France", country: "France" },
  DLH: { icao: "DLH", iata: "LH", name: "Lufthansa", country: "Germany" },
  KLM: { icao: "KLM", iata: "KL", name: "KLM Royal Dutch Airlines", country: "Netherlands" },
  IBE: { icao: "IBE", iata: "IB", name: "Iberia", country: "Spain" },
  TAP: { icao: "TAP", iata: "TP", name: "TAP Air Portugal", country: "Portugal" },
  SAS: { icao: "SAS", iata: "SK", name: "Scandinavian Airlines", country: "Sweden" },
  FIN: { icao: "FIN", iata: "AY", name: "Finnair", country: "Finland" },
  SWR: { icao: "SWR", iata: "LX", name: "Swiss International Air Lines", country: "Switzerland" },
  AUA: { icao: "AUA", iata: "OS", name: "Austrian Airlines", country: "Austria" },
  BEL: { icao: "BEL", iata: "SN", name: "Brussels Airlines", country: "Belgium" },
  LOT: { icao: "LOT", iata: "LO", name: "LOT Polish Airlines", country: "Poland" },
  CSA: { icao: "CSA", iata: "OK", name: "Czech Airlines", country: "Czech Republic" },
  AZA: { icao: "AZA", iata: "AZ", name: "ITA Airways", country: "Italy" },
  EZY: { icao: "EZY", iata: "U2", name: "easyJet", country: "United Kingdom" },
  RYR: { icao: "RYR", iata: "FR", name: "Ryanair", country: "Ireland" },
  WZZ: { icao: "WZZ", iata: "W6", name: "Wizz Air", country: "Hungary" },
  VLG: { icao: "VLG", iata: "VY", name: "Vueling", country: "Spain" },
  NAX: { icao: "NAX", iata: "DY", name: "Norwegian Air Shuttle", country: "Norway" },
  THY: { icao: "THY", iata: "TK", name: "Turkish Airlines", country: "Turkey" },
  AEE: { icao: "AEE", iata: "A3", name: "Aegean Airlines", country: "Greece" },
  AFL: { icao: "AFL", iata: "SU", name: "Aeroflot", country: "Russia" },
  SBI: { icao: "SBI", iata: "S7", name: "S7 Airlines", country: "Russia" },
  AHY: { icao: "AHY", iata: "J2", name: "Azerbaijan Airlines", country: "Azerbaijan" },
  TGZ: { icao: "TGZ", iata: "T5", name: "Turkmenistan Airlines", country: "Turkmenistan" },
  UZB: { icao: "UZB", iata: "HY", name: "Uzbekistan Airways", country: "Uzbekistan" },
  KZR: { icao: "KZR", iata: "KC", name: "Air Astana", country: "Kazakhstan" },
  EIN: { icao: "EIN", iata: "EI", name: "Aer Lingus", country: "Ireland" },
  ICE: { icao: "ICE", iata: "FI", name: "Icelandair", country: "Iceland" },
  SXS: { icao: "SXS", iata: "XQ", name: "SunExpress", country: "Turkey" },
  PGT: { icao: "PGT", iata: "PC", name: "Pegasus Airlines", country: "Turkey" },
  TRA: { icao: "TRA", iata: "HV", name: "Transavia", country: "Netherlands" },
  EWG: { icao: "EWG", iata: "EW", name: "Eurowings", country: "Germany" },
  BER: { icao: "BER", iata: "AB", name: "Air Berlin (now defunct)", country: "Germany" },
  VOE: { icao: "VOE", iata: "V7", name: "Volotea", country: "Spain" },
  TVS: { icao: "TVS", iata: "QS", name: "SmartWings", country: "Czech Republic" },
  BAL: { icao: "BAL", iata: "TF", name: "Braathens Regional", country: "Sweden" },
  // ── Middle East ──
  UAE: { icao: "UAE", iata: "EK", name: "Emirates", country: "United Arab Emirates" },
  QTR: { icao: "QTR", iata: "QR", name: "Qatar Airways", country: "Qatar" },
  ETD: { icao: "ETD", iata: "EY", name: "Etihad Airways", country: "United Arab Emirates" },
  SVA: { icao: "SVA", iata: "SV", name: "Saudia", country: "Saudi Arabia" },
  MEA: { icao: "MEA", iata: "ME", name: "Middle East Airlines", country: "Lebanon" },
  ELY: { icao: "ELY", iata: "LY", name: "El Al", country: "Israel" },
  RJA: { icao: "RJA", iata: "RJ", name: "Royal Jordanian", country: "Jordan" },
  GFA: { icao: "GFA", iata: "GF", name: "Gulf Air", country: "Bahrain" },
  OMA: { icao: "OMA", iata: "WY", name: "Oman Air", country: "Oman" },
  KAC: { icao: "KAC", iata: "KU", name: "Kuwait Airways", country: "Kuwait" },
  FDB: { icao: "FDB", iata: "FZ", name: "flydubai", country: "United Arab Emirates" },
  ABY: { icao: "ABY", iata: "G9", name: "Air Arabia", country: "United Arab Emirates" },
  FDX: { icao: "FDX", iata: "FX", name: "FedEx Express", country: "United States" },
  NAS: { icao: "NAS", iata: "XY", name: "flynas", country: "Saudi Arabia" },
  // ── Asia-Pacific ──
  SIA: { icao: "SIA", iata: "SQ", name: "Singapore Airlines", country: "Singapore" },
  CPA: { icao: "CPA", iata: "CX", name: "Cathay Pacific", country: "Hong Kong" },
  ANA: { icao: "ANA", iata: "NH", name: "All Nippon Airways", country: "Japan" },
  JAL: { icao: "JAL", iata: "JL", name: "Japan Airlines", country: "Japan" },
  CCA: { icao: "CCA", iata: "CA", name: "Air China", country: "China" },
  CSN: { icao: "CSN", iata: "CZ", name: "China Southern Airlines", country: "China" },
  CES: { icao: "CES", iata: "MU", name: "China Eastern Airlines", country: "China" },
  HXA: { icao: "HXA", iata: "HX", name: "Hong Kong Airlines", country: "Hong Kong" },
  CHH: { icao: "CHH", iata: "HU", name: "Hainan Airlines", country: "China" },
  CSC: { icao: "CSC", iata: "SC", name: "Shandong Airlines", country: "China" },
  CXA: { icao: "CXA", iata: "MF", name: "Xiamen Airlines", country: "China" },
  CSZ: { icao: "CSZ", iata: "ZH", name: "Shenzhen Airlines", country: "China" },
  KAL: { icao: "KAL", iata: "KE", name: "Korean Air", country: "South Korea" },
  AAR: { icao: "AAR", iata: "OZ", name: "Asiana Airlines", country: "South Korea" },
  THA: { icao: "THA", iata: "TG", name: "Thai Airways", country: "Thailand" },
  MAS: { icao: "MAS", iata: "MH", name: "Malaysia Airlines", country: "Malaysia" },
  GIA: { icao: "GIA", iata: "GA", name: "Garuda Indonesia", country: "Indonesia" },
  PAL: { icao: "PAL", iata: "PR", name: "Philippine Airlines", country: "Philippines" },
  VNA: { icao: "VNA", iata: "VN", name: "Vietnam Airlines", country: "Vietnam" },
  AIC: { icao: "AIC", iata: "AI", name: "Air India", country: "India" },
  IGO: { icao: "IGO", iata: "6E", name: "IndiGo", country: "India" },
  SEJ: { icao: "SEJ", iata: "SG", name: "SpiceJet", country: "India" },
  AXB: { icao: "AXB", iata: "IX", name: "Air India Express", country: "India" },
  AKX: { icao: "AKX", iata: "QZ", name: "AirAsia X", country: "Malaysia" },
  AXM: { icao: "AXM", iata: "AK", name: "AirAsia", country: "Malaysia" },
  JSA: { icao: "JSA", iata: "JQ", name: "Jetstar Airways", country: "Australia" },
  SLK: { icao: "SLK", iata: "TR", name: "Scoot", country: "Singapore" },
  CEB: { icao: "CEB", iata: "5J", name: "Cebu Pacific", country: "Philippines" },
  BKP: { icao: "BKP", iata: "KD", name: "Bangkok Airways", country: "Thailand" },
  TWB: { icao: "TWB", iata: "WA", name: "Thai Smile", country: "Thailand" },
  VJC: { icao: "VJC", iata: "VJ", name: "VietJet Air", country: "Vietnam" },
  APJ: { icao: "APJ", iata: "MM", name: "Peach Aviation", country: "Japan" },
  JJP: { icao: "JJP", iata: "GK", name: "Jetstar Japan", country: "Japan" },
  SJY: { icao: "SJY", iata: "7C", name: "Jeju Air", country: "South Korea" },
  TWR: { icao: "TWR", iata: "TW", name: "T'way Air", country: "South Korea" },
  QFA: { icao: "QFA", iata: "QF", name: "Qantas", country: "Australia" },
  ANZ: { icao: "ANZ", iata: "NZ", name: "Air New Zealand", country: "New Zealand" },
  VOZ: { icao: "VOZ", iata: "VA", name: "Virgin Australia", country: "Australia" },
  REX: { icao: "REX", iata: "ZL", name: "Rex Airlines", country: "Australia" },
  FJI: { icao: "FJI", iata: "FJ", name: "Fiji Airways", country: "Fiji" },
  PIA: { icao: "PIA", iata: "PK", name: "Pakistan International Airlines", country: "Pakistan" },
  SLJ: { icao: "SLJ", iata: "UL", name: "SriLankan Airlines", country: "Sri Lanka" },
  ALK: { icao: "ALK", iata: "UL", name: "SriLankan Airlines", country: "Sri Lanka" },
  BNG: { icao: "BNG", iata: "BG", name: "Biman Bangladesh Airlines", country: "Bangladesh" },
  NPL: { icao: "NPL", iata: "RA", name: "Nepal Airlines", country: "Nepal" },
  MGL: { icao: "MGL", iata: "OM", name: "MIAT Mongolian Airlines", country: "Mongolia" },
  // ── Africa ──
  ETH: { icao: "ETH", iata: "ET", name: "Ethiopian Airlines", country: "Ethiopia" },
  SAA: { icao: "SAA", iata: "SA", name: "South African Airways", country: "South Africa" },
  KQA: { icao: "KQA", iata: "KQ", name: "Kenya Airways", country: "Kenya" },
  RNA: { icao: "RNA", iata: "WB", name: "RwandAir", country: "Rwanda" },
  MSR: { icao: "MSR", iata: "MS", name: "EgyptAir", country: "Egypt" },
  RAM: { icao: "RAM", iata: "AT", name: "Royal Air Maroc", country: "Morocco" },
  DAH: { icao: "DAH", iata: "AH", name: "Air Algérie", country: "Algeria" },
  TAR: { icao: "TAR", iata: "TU", name: "Tunisair", country: "Tunisia" },
  NIG: { icao: "NIG", iata: "WT", name: "Air Nigeria", country: "Nigeria" },
  // ── Latin America ──
  LAN: { icao: "LAN", iata: "LA", name: "LATAM Airlines", country: "Chile" },
  ARG: { icao: "ARG", iata: "AR", name: "Aerolineas Argentinas", country: "Argentina" },
  GLO: { icao: "GLO", iata: "G3", name: "Gol Linhas Aéreas", country: "Brazil" },
  TAM: { icao: "TAM", iata: "JJ", name: "LATAM Brasil", country: "Brazil" },
  AZU: { icao: "AZU", iata: "AD", name: "Azul Brazilian Airlines", country: "Brazil" },
  CMP: { icao: "CMP", iata: "CM", name: "Copa Airlines", country: "Panama" },
  AVA: { icao: "AVA", iata: "AV", name: "Avianca", country: "Colombia" },
  BWI: { icao: "BWI", iata: "BW", name: "Caribbean Airlines", country: "Trinidad & Tobago" },
  // ── Cargo ──
  UPS: { icao: "UPS", iata: "5X", name: "UPS Airlines", country: "United States" },
  GTI: { icao: "GTI", iata: "GT", name: "Atlas Air", country: "United States" },
  CLX: { icao: "CLX", iata: "CV", name: "Cargolux", country: "Luxembourg" },
  KAB: { icao: "KAB", iata: "K4", name: "Kalitta Air", country: "United States" },
  ABW: { icao: "ABW", iata: "RU", name: "AirBridge Cargo", country: "Russia" },
  CAO: { icao: "CAO", iata: "2R", name: "Air China Cargo", country: "China" },
  BOX: { icao: "BOX", iata: "BX", name: "Korean Air Cargo", country: "South Korea" },
  SQC: { icao: "SQC", iata: "SQ", name: "Singapore Airlines Cargo", country: "Singapore" },
  MPH: { icao: "MPH", iata: "MP", name: "Martinair", country: "Netherlands" },
  QYC: { icao: "QYC", iata: "QY", name: "European Air Transport (DHL)", country: "Belgium" },
  BCS: { icao: "BCS", iata: "D0", name: "DHL Air", country: "United Kingdom" },
  DHL: { icao: "DHL", iata: "ES", name: "DHL Aviation", country: "United States" },
  // ── Business / Charter ──
  TVF: { icao: "TVF", iata: "TO", name: "Transavia France", country: "France" },
  TOM: { icao: "TOM", iata: "BY", name: "TUI Airways", country: "United Kingdom" },
  JAF: { icao: "JAF", iata: "JN", name: "Jet Airways (defunct)", country: "India" },
  CFE: { icao: "CFE", iata: "5V", name: "BA CityFlyer", country: "United Kingdom" },
  LOG: { icao: "LOG", iata: "LM", name: "Loganair", country: "United Kingdom" },
  SHT: { icao: "SHT", iata: "BA", name: "British Airways Shuttle", country: "United Kingdom" },
  VIR: { icao: "VIR", iata: "VS", name: "Virgin Atlantic", country: "United Kingdom" },
  // ── Additional carriers ──
  THT: { icao: "THT", iata: "TN", name: "Air Tahiti Nui", country: "French Polynesia" },
  DKH: { icao: "DKH", iata: "HO", name: "Juneyao Airlines", country: "China" },
  CDC: { icao: "CDC", iata: "CI", name: "China Airlines", country: "Taiwan" },
  EVA: { icao: "EVA", iata: "BR", name: "EVA Air", country: "Taiwan" },
  TGW: { icao: "TGW", iata: "X3", name: "TUI fly Deutschland", country: "Germany" },
  MAC: { icao: "MAC", iata: "FS", name: "Air Macau", country: "Macau" },
  RBA: { icao: "RBA", iata: "BI", name: "Royal Brunei Airlines", country: "Brunei" },
  MXD: { icao: "MXD", iata: "MX", name: "Breeze Airways", country: "United States" },
  TAI: { icao: "TAI", iata: "TA", name: "TACA International Airlines", country: "El Salvador" },
  LNI: { icao: "LNI", iata: "JT", name: "Lion Air", country: "Indonesia" },
  BTK: { icao: "BTK", iata: "ID", name: "Batik Air", country: "Indonesia" },
  SWD: { icao: "SWD", iata: "WO", name: "Swoop (WestJet subsidiary)", country: "Canada" },
  SWG: { icao: "SWG", iata: "4N", name: "Air North", country: "Canada" },
};

export function inferAirlineFromCallsign(callsign: string | null): AirlinePrefix | null {
  if (!callsign) return null;

  const cleaned = callsign.trim().toUpperCase();

  // Extract airline code (first 3 letters typically)
  const match = cleaned.match(/^([A-Z]{3})/);
  if (!match) return null;

  const prefix = match[1];
  return airlinePrefixes[prefix] || null;
}
