import type { Flight } from "@/lib/opensky";

function nowSeconds(nowMs = Date.now()) {
  return Math.floor(nowMs / 1000);
}

export function buildDemoFlightPayload(nowMs = Date.now()) {
  const now = nowSeconds(nowMs);
  const flights: Flight[] = [
    {
      icao24: "a1b2c3",
      callsign: "SKY101",
      origin_country: "United States",
      time_position: now - 3,
      last_contact: now - 2,
      longitude: -73.7781,
      latitude: 40.6413,
      baro_altitude: 3100,
      on_ground: false,
      velocity: 145,
      true_track: 72,
      vertical_rate: 4.2,
      sensors: null,
      geo_altitude: 3180,
      squawk: "1200",
      spi: false,
      position_source: 0,
      category: 5,
      data_source: "demo",
      ml_anomaly_score: 0.04,
      predicted_path: [],
      prediction_confidence: 0.72,
      source_confidence: 0.99,
      source_provenance: ["demo"],
      source_conflicts: [],
    },
    {
      icao24: "b2c3d4",
      callsign: "MED770",
      origin_country: "United States",
      time_position: now - 8,
      last_contact: now - 5,
      longitude: -118.2437,
      latitude: 34.0522,
      baro_altitude: 950,
      on_ground: false,
      velocity: 118,
      true_track: 282,
      vertical_rate: -6.4,
      sensors: null,
      geo_altitude: 990,
      squawk: "7700",
      spi: false,
      position_source: 0,
      category: 3,
      data_source: "demo",
      ml_anomaly_score: -0.72,
      predicted_path: [],
      prediction_confidence: 0.64,
      source_confidence: 0.99,
      source_provenance: ["demo"],
      source_conflicts: [],
    },
    {
      icao24: "c3d4e5",
      callsign: "OCEAN5",
      origin_country: "Iceland",
      time_position: now - 12,
      last_contact: now - 10,
      longitude: -22.6056,
      latitude: 63.985,
      baro_altitude: 11200,
      on_ground: false,
      velocity: 245,
      true_track: 244,
      vertical_rate: 0.1,
      sensors: null,
      geo_altitude: 11310,
      squawk: "2000",
      spi: false,
      position_source: 6,
      category: 4,
      data_source: "satellite",
      ml_anomaly_score: 0.02,
      predicted_path: [],
      prediction_confidence: 0.69,
      source_confidence: 0.78,
      source_provenance: ["satellite"],
      source_conflicts: [],
    },
  ];

  return {
    time: now,
    flights,
    states: flights,
    authenticated: false,
    source: "demo",
    count: flights.length,
    stale_count: 0,
    max_age_seconds: 12,
    source_counts: { demo: 2, satellite: 1 },
    source_health: {
      demo: {
        status: "ok",
        enabled: true,
        confidence_score: 0.99,
        last_success_at: new Date(nowMs).toISOString(),
        consecutive_failures: 0,
      },
      satellite: {
        status: "ok",
        enabled: true,
        confidence_score: 0.78,
        last_success_at: new Date(nowMs).toISOString(),
        consecutive_failures: 0,
      },
    },
    source_conflict_count: 0,
    degraded: false,
    coverage: {
      demo_mode: true,
      public_sources_only: false,
    },
  };
}

export function buildDemoSatellitePayload(nowMs = Date.now()) {
  const now = nowSeconds(nowMs);
  return {
    time: now,
    generated_at: new Date(nowMs).toISOString(),
    source: "demo",
    status: "ok",
    propagator: "fixed-demo",
    satellites: [
      {
        id: "25544",
        name: "ISS (DEMO)",
        group: "stations",
        group_label: "Space stations",
        latitude: 18.2,
        longitude: 73.8,
        altitude_km: 420,
        velocity_kms: 7.66,
        inclination_deg: 51.64,
        period_minutes: 92.9,
        mean_motion_rev_day: 15.49,
        tle_epoch: new Date(nowMs).toISOString(),
        epoch_age_hours: 0,
        orbit_quality: "fresh",
        source: "demo",
        propagator: "fixed-demo",
      },
    ],
    count: 1,
    source_counts: { stations: 1 },
    groups: [
      {
        key: "stations",
        name: "Space stations",
        celestrak_group: "stations",
        count: 1,
        color: "#22c55e",
      },
    ],
    errors: {},
    coverage: {
      public_sources_only: false,
      demo_mode: true,
      fallback_groups: [],
    },
  };
}
